# --- Configurações de Persistência e Log (mantém as mesmas) ---
listener 1883
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# --- Configurações de Autenticação ---
password_file /mosquitto/config/mosquitto.passwd
allow_anonymous false
