# configs/telegraf.conf
#
# Arquivo de configuração do Telegraf para a stack de monitoramento
# Telegraf coleta dados do Mosquitto e envia para o InfluxDB

# Configurações do agente Telegraf
[agent]
  # Intervalo de coleta para todos os plugins
  interval = "10s"
  # Limite para o buffer de métricas
  metric_buffer_limit = 10000

#
# PLUGIN DE SAÍDA
#

# Envia métricas para o InfluxDB 2.0
[[outputs.influxdb_v2]]
  # URL do serviço InfluxDB dentro da rede do Docker
  urls = ["http://influxdb:8086"]
  # Token de autenticação que você configurou no InfluxDB
  token = "-GdXwoQ0tU-G7vWVgx0nh1B8bu9XnSjVWrzwNfB8t2XFO546ebp92i62Cdz2PJXhHdKUuYtPySIkcQfojkFcxA=="
  # Organização e bucket de destino
  organization = "setta"
  bucket = "pgswifi"

#
# PLUGIN DE ENTRADA
#

# Lê métricas do Mosquitto
[[inputs.mqtt_consumer]]
  # URL do serviço Mosquitto dentro da rede do Docker
  servers = ["tcp://mosquitto:1883"]
  # Tópicos que o Telegraf irá assinar
  topics = [
    "/#",
    "/",
  ]
  # Formato dos dados recebidos do MQTT
  data_format = "json"
  # Credenciais de autenticação para o Mosquitto
  username = "telegraf"
  password = "aV2zwMaueKruh0Bp5R0tSOQk13lv9FXz0aCeRM7dCTKrSrzyKd5Q6Cm263gdO1lI"

#
# PROCESSADOR DE DADOS
#

# Renomeia campos antes de enviar para o InfluxDB
[[processors.rename]]
  [[processors.rename.replace]]
    field = "vasao"
    dest = "vazao"
